### ISSUE TITLE
Account for different baloosearch binary name

### ISSUE THREAD

**Issue by Lxtharia** [IT-Hock/ulauncher-baloo#2]
It seems there is some inconsistency in the binary name. I use Arch (btw) and the binary is called `baloosearch6`, yet it seems on different distros, it's simply called `baloosearch`.

Would be perfect if both binary names are tried :)

**Comment by Subtixx** [comment]
Should be fixed in https://github.com/IT-Hock/ulauncher-baloo/tree/fix-add-baloo-executable-detect

However, I think we should add a settings page for both "new" options (terminal and baloo executable) to let the user modify the path if he is not happy with the autodetected ones.

EDIT:
I use arch too, so it's funny that yours is called different

**Comment by Subtixx** [comment]
Okay I thought about it and decided not to include my "fix" of the fix-add-baloo-executable-detect branch. Instead I rewrote both as described above.

The actual fix is made in 2a29d850052e9412c80f678a38f6110313db5838 and was already merged into main. This adds 2 new preferences.
1. For the baloosearch executable name (although leaving it empty will try to "auto-detect" it, basically tries baloosearch, baloosearch5, baloosearch6 and uses the one that is available in path).
2. It lets a user choose the terminal emulator using a drop-down in settings.

Hope this statisfies you, I will close this issue until further notice. Thanks for bringing this to my attention!

**Comment by Lxtharia** [comment]
Thanks for the quick fix + improvement! :)

I am curious about why the binary name is different. I have baloo v6.7.0-1, installed via pacman, it's the same on both my arch devices.

**Comment by Subtixx** [comment]
I do have a baloosearch6 but I also somehow have a baloosearch symlink to said baloosearch6. Very strange
